# File di configurazione di ImmuDB

address = "192.168.56.10"
admin-password = 'changeme'
auth = true
certificate = ''
clientcas = ''
dbname = 'logs_immudb'
detached = 'false'
#devmode = true
dir = '/var/lib/immudb'
network = 'tcp'
port = 3322

# Log path with filename
logfile = 'immudb.log'

mtls = false
pidfile = '/var/lib/immudb/immudb.pid'
PKEY = ''
log-level = "DEBUG"

[database]
gc-enabled = 'true'
retention-period = "24h"
